apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
        - name: microservice-a
          image: "<IMAGE_URI>"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-a
spec:
  type: LoadBalancer
  selector:
    app: microservice-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
